# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
version: '3.3'

services:
  client:
    image: opencrvs/ocrvs-client:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: unless-stopped
  dashboards:
    image: opencrvs/ocrvs-dashboards:${VERSION:-latest}
    build:
      context: ./packages/dashboards
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - OPENCRVS_METABASE_SITE_NAME=taopencrvs
      - OPENCRVS_METABASE_SITE_URL=http://192.168.0.50:4444
      - OPENCRVS_METABASE_DB_HOST=192.168.0.50
      - OPENCRVS_METABASE_MAP_URL=http://192.168.0.50:3040/content/farajaland-map.geojson
      - OPENCRVS_METABASE_DB_USER=""
      - OPENCRVS_METABASE_DB_PASS=""
      - OPENCRVS_METABASE_DB_AUTH_DB=""
      - OPENCRVS_METABASE_MAP_NAME=Farajaland
      - OPENCRVS_METABASE_MAP_REGION_KEY=State
      - OPENCRVS_METABASE_MAP_REGION_NAME=State
    ports:
      - "3000:3000"
  components:
    image: opencrvs/ocrvs-components:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/components/Dockerfile
    restart: unless-stopped
  login:
    image: opencrvs/ocrvs-login:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/login/Dockerfile
    restart: unless-stopped
    environment:
      - AUTH_API_URL=http://192.168.0.50:4040
    ports:
      - "3020:80"
  gateway:
    image: opencrvs/ocrvs-gateway:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/gateway/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_HOST=192.168.0.50
      - CONFIG_SMS_CODE_EXPIRY_SECONDS=600
      - CONFIG_TOKEN_EXPIRY_SECONDS=604800
      - NODE_ENV=development
      - FHIR_URL=http://192.168.0.50:5001/fhir
      - HEARTH_URL=http://hearth:3447/fhir
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - SEARCH_URL=http://search:9090/
      - METRICS_URL=http://metrics:1050
      - AUTH_URL=http://auth:4040
      - COUNTRY_CONFIG_URL=http://192.168.0.50:3040
      - NOTIFICATION_URL=http://notification:2020/
      - WORKFLOW_URL=http://workflow:5050/
      - APPLICATION_CONFIG_URL=http://config:2021/
      - WEBHOOKS_URL=http://webhooks:2525/
      - CHECK_INVALID_TOKEN=true
      - MINIO_BUCKET=ocrvs
      - DOCUMENTS_URL=http://documents:9050
    ports:
      - '7070:7070'
  # User facing services
  workflow:
    image: opencrvs/ocrvs-workflow:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/workflow/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - COUNTRY_CONFIG_URL=http://192.168.0.50:3040
      - HEARTH_URL=http://hearth:3447/fhir
      - OPENHIM_URL=http://192.168.0.50:5001
      - APPLICATION_CONFIG_URL=http://config:2021/
      - COUNTRY=${COUNTRY:-bgd} # PEN_TEST change to gbr
    ports:
      - '5050:5050'
  search:
    image: opencrvs/ocrvs-search:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/search/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - ES_HOST=192.168.0.50:9200
      - HEARTH_URL=http://hearth:3447/fhir
    ports:
      - '9090:9090'
  metrics:
    image: opencrvs/ocrvs-metrics:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/metrics/Dockerfile
    restart: unless-stopped
    environment:
      - INFLUX_HOST=192.168.0.50
      - INFLUX_PORT=8086
      - INFLUX_DB=ocrvs
      - COUNTRY_CONFIG_URL=http://192.168.0.50:3040/
      - CONFIG_API_URL=http://config:2021
      - FHIR_URL=http://192.168.0.50:5001/fhir
      - MONGO_URL=mongodb://192.168.0.50:27017/metrics
      - HEARTH_MONGO_URL=mongodb://192.168.0.50:27017/hearth-dev
      - DASHBOARD_MONGO_URL=mongodb://192.168.0.50:27017/performance
      - SEARCH_URL=http://search:9090/
      - USER_MANAGEMENT_URL=http://user-mgnt:3030
      - DOCUMENTS_URL=http://documents:9050
    ports:
      - '1050:1050'
  # END User facing services
  scheduler:
    image: opencrvs/ocrvs-scheduler:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/scheduler/Dockerfile
    environment:
      - NODE_ENV=development
      - METRICS_URL=http://metrics:1050
      - OPENHIM_MONGO_URL=mongodb://192.168.0.50:27017/openhim-dev
  auth:
    image: opencrvs/ocrvs-auth:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_HOST=192.168.0.50
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - CONFIG_TOKEN_EXPIRY_SECONDS=604800
      - CONFIG_SMS_CODE_EXPIRY_SECONDS=600
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - METRICS_URL=http://metrics:1050
    ports:
      - '4040:4040'
  user-mgnt:
    image: opencrvs/ocrvs-user-mgnt:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/user-mgnt/Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://192.168.0.50:27017/user-mgnt
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - FHIR_URL=http://192.168.0.50:5001/fhir
      - HOST=0.0.0.0
      - METRICS_URL=http://metrics:1050
    ports:
      - '3030:3030'
  webhooks:
    image: opencrvs/ocrvs-webhooks:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/webhooks/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis://192.168.0.50:6379
      - MONGO_URL=mongodb://192.168.0.50:27017/webhooks
      - AUTH_URL=http://auth:4040
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - FHIR_URL=http://192.168.0.50:5001/fhir
      - HOST=0.0.0.0
      - CHECK_INVALID_TOKEN=true
    ports:
      - '2525:2525'
  notification:
    image: opencrvs/ocrvs-notification:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/notification/Dockerfile
    restart: unless-stopped
    environment:
      - COUNTRY=${COUNTRY:-bgd}
      - HOST=0.0.0.0
      - COUNTRY_CONFIG_URL=http://192.168.0.50:3040
    ports:
      - '2020:2020'
  config:
    image: opencrvs/ocrvs-config:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/config/Dockerfile
    restart: unless-stopped
    environment:
      - AUTH_URL=http://auth:4040
      - COUNTRY_CONFIG_URL=http://192.168.0.50:3040
      - HOST=0.0.0.0
      - PORT=2021
      - MONGO_URL=mongodb://192.168.0.50:27017/application-config
      - FHIR_URL=http://192.168.0.50:5001/fhir
      - SEARCH_URL=http://search:9090/
      - METRICS_URL=http://metrics:1050
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - GATEWAY_URL=http://gateway:7070/
      - DOCUMENTS_URL=http://documents:9050
      - CHECK_INVALID_TOKEN=true
    ports:
      - "2021:80"
  migration:
    image: opencrvs/ocrvs-migration:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/migration/Dockerfile
    restart: unless-stopped
    environment:
      - USER_MGNT_MONGO_URL=mongodb://192.168.0.50:27017/user-mgnt
      - APPLICATION_CONFIG_MONGO_URL=mongodb://192.168.0.50:27017/application-config
      - HEARTH_MONGO_URL=mongodb://192.168.0.50:27017/hearth-dev
      - DASHBOARD_MONGO_URL=mongodb://192.168.0.50:27017/performance
      - OPENHIM_MONGO_URL=mongodb://192.168.0.50:27017/openhim-dev
      - PERFORMANCE_MONGO_URL=mongodb://192.168.0.50/performance
      - ES_HOST=192.168.0.50:9200
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
      - INFLUX_DB=ocrvs
      - WAIT_HOSTS=192.168.0.50:27017,192.168.0.50:8086,192.168.0.50:9000,192.168.0.50:9200
    ports:
      - '9000:9000'
  documents:
    image: opencrvs/ocrvs-documents:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/documents/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - COUNTRY_CONFIG_URL=http://192.168.0.50:3040
      - MINIO_HOST=192.168.0.50
    ports:
      - '9050:9050'
